eureka:
  instance:
    secure-port-enabled: false
    hostname: auth.server.com
    instance-id: ${eureka.instance.hostname}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://jerry:jerry@127.0.0.1:8888/eureka/
    fetch-registry: false
server:
  port: 8001
  servlet:
    session:
      cookie:
        name: AUTH_SERVER_SESSIONID
spring:
  application:
    name: jerry's auth server
  datasource:
    url: jdbc:h2:file:./auth_server/database/org
    username: jerry
    password: jerry
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update